# Generated by Django 3.1.6 on 2021-02-21 19:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('node_frames', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodeframe',
            name='creation_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
