# Generated by Django 3.1.6 on 2021-03-22 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('node_frames', '0005_arc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arc',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arcs', to='node_frames.nodeframe'),
        ),
        migrations.AlterField(
            model_name='nodeframe',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='nodeframe',
            name='name',
            field=models.CharField(max_length=72, null=True),
        ),
    ]
